(() => {
  const DEFAULTS={autoAccept:true,dpsEnabled:true,panelCollapsed:false,compactMode:false};
  const state={settings:{...DEFAULTS},players:new Map(),startedAt:0,lastDamageAt:0,renderQueued:false,seenLines:new WeakSet(),clickLock:0,recentDamage:new Map(),entities:new Map(),classes:new Map(),playerIds:new Set(),pendingHits:[]};
  const colors=["#d43d9a","#4299d1","#39bf74","#dc5b5b","#b184e8","#e2a443"];
  const classColors={MS:"#8f2635",RP:"#a87819",EK:"#174f7a",ED:"#268b57"};
  const cleanName=v=>String(v||"Desconhecido").replace(/\s+/g," ").trim().slice(0,28);
  function toNumber(v){if(typeof v==="number")return Number.isFinite(v)?Math.abs(v):0;if(typeof v!=="string")return 0;const t=v.trim().replace(/\s/g,"");if(!/^-?[\d.,]+$/.test(t))return 0;const n=t.includes(".")&&t.includes(",")?t.replace(/\./g,"").replace(",","."):t.replace(",",".");return Math.abs(Number(n))||0;}
  function playerName(){return cleanName(document.querySelector("header strong, [role='banner'] strong")?.textContent||"Você");}
  function canonicalName(name){name=cleanName(name);return /^(você|voce|you|self|me)$/i.test(name)?playerName():name;}
  function updateDamageMap(map,name,amount,critical){const item=map.get(name)||{name,damage:0,hits:0,criticalHits:0,maxHit:0};item.damage+=amount;item.hits++;item.maxHit=Math.max(item.maxHit,amount);if(critical)item.criticalHits++;map.set(name,item);}
  function addDamage(name,amount,source="unknown",critical=false){amount=toNumber(amount);if(!amount||amount>1e12)return;name=canonicalName(name);const now=Date.now(),signature=`${name.toLocaleLowerCase("pt-BR")}|${amount}`;const recent=state.recentDamage.get(signature);if(recent&&recent.source!==source&&now-recent.at<1200){state.recentDamage.delete(signature);return;}state.recentDamage.set(signature,{source,at:now});if(state.recentDamage.size>300)for(const [key,value] of state.recentDamage)if(now-value.at>5000)state.recentDamage.delete(key);if(!state.startedAt)state.startedAt=now;state.lastDamageAt=now;updateDamageMap(state.players,name,amount,critical);scheduleRender();}
  function entityKey(id){return id===null||id===undefined?"":String(id);}
  function classAbbreviation(value){if(value&&typeof value==="object")value=value.name??value.title??value.code??value.id;const numeric={1:"MS",2:"ED",3:"RP",4:"EK",5:"MS",6:"ED",7:"RP",8:"EK"};if(typeof value==="number"||/^\d+$/.test(String(value||"")))return numeric[Number(value)]||"";const text=String(value||"").trim().toLocaleLowerCase("pt-BR");if(!text)return"";if(/^(ek|elite knight|knight)$/.test(text))return"EK";if(/^(rp|royal paladin|paladin)$/.test(text))return"RP";if(/^(ed|elder druid|druid)$/.test(text))return"ED";if(/^(ms|master sorcerer|sorcerer)$/.test(text))return"MS";return"";}
  function entityLabel(key){const name=state.entities.get(key),klass=state.classes.get(key);return name?`${name}${klass?` [${klass}]`:""}`:"";}
  function mergeRenamed(map,oldLabel,newLabel){if(!map.has(oldLabel))return;const old=map.get(oldLabel),current=map.get(newLabel)||{name:newLabel,damage:0,hits:0,criticalHits:0,maxHit:0};current.damage+=old.damage;current.hits+=old.hits;current.criticalHits+=old.criticalHits||0;current.maxHit=Math.max(current.maxHit||0,old.maxHit||0);map.set(newLabel,current);map.delete(oldLabel);}
  function rememberEntity(value){const id=value.id??value.playerId??value.creatureId??value.characterId,name=value.name??value.playerName??value.characterName;if(id===undefined)return;const key=entityKey(id),oldLabel=entityLabel(key);if(typeof name==="string"&&name.trim())state.entities.set(key,cleanName(name));const klass=classAbbreviation(value.vocation??value.vocationName??value.class??value.className??value.profession);if(klass)state.classes.set(key,klass);if(value.vocation!==undefined||value.vocationName!==undefined||value.class!==undefined||value.className!==undefined||value.healthPercent!==undefined&&value.manaPercent!==undefined||value.isPlayer===true||value.kind==="player")state.playerIds.add(key);const newLabel=entityLabel(key);if(oldLabel&&newLabel&&oldLabel!==newLabel)mergeRenamed(state.players,oldLabel,newLabel);if(!newLabel)return;for(let i=state.pendingHits.length-1;i>=0;i--){const hit=state.pendingHits[i];if(hit.attackerId===key&&state.playerIds.has(key)){addDamage(newLabel,hit.value,"network",hit.critical);state.pendingHits.splice(i,1);}}}
  function scanObject(value,depth=0){if(!value||depth>9)return;if(Array.isArray(value)){value.forEach(v=>scanObject(v,depth+1));return;}if(typeof value!=="object")return;rememberEntity(value);const type=String(value.type||value.event||value.action||value.kind||"");if(/^(creature-hit|creatureHit|hit)$/i.test(type)&&value.attackerId!==undefined&&toNumber(value.value)){const attackerId=entityKey(value.attackerId);if(value.attackerName&&value.isPlayer===true){state.entities.set(attackerId,cleanName(value.attackerName));state.playerIds.add(attackerId);}const name=entityLabel(attackerId),critical=value.critical===true||value.isCritical===true;if(name&&state.playerIds.has(attackerId))addDamage(name,value.value,"network",critical);else{state.pendingHits.push({attackerId,value:value.value,critical,at:Date.now()});if(state.pendingHits.length>300)state.pendingHits.splice(0,state.pendingHits.length-300);}return;}Object.keys(value).forEach(key=>scanObject(value[key],depth+1));}
  function parsePacket(raw){if(typeof raw!=="string")return;const text=raw.trim();if(!text||text.length>2e6)return;try{scanObject(JSON.parse(text));return;}catch(_){}parseCombatText(text);}
  function parseCombatText(text){const patterns=[/(?:^|\n)(?:\s*\d{1,2}:\d{2}(?::\d{2})?\s*)?(?:⚔️?\s*)?Você\s+acertou\s+.+?\s+causando\s+([\d.,]+)\.?\s*(?=\n|$)/giu,/(?:^|\n)(?:\s*\d{1,2}:\d{2}(?::\d{2})?\s*)?(?:⚔️?\s*)?([\p{L}\d _.-]{2,28})\s+acertou\s+.+?\s+causando\s+([\d.,]+)\.?\s*(?=\n|$)/giu,/(?:^|\n)\s*([\p{L}\d _.-]{2,28})\s+(?:causou|deu|hit|deals?)\s+([\d.,]+)\s+(?:de\s+)?(?:dano|damage)/giu,/(?:^|\n)\s*([\p{L}\d _.-]{2,28})\s*[:\-]\s*([\d.,]+)\s*(?:dano|damage|dmg)\b/giu,/(?:damage|dmg)[^\d]{0,12}([\d.,]+)[^\p{L}\d]{1,8}(?:by|por)\s+([\p{L}\d _.-]{2,28})/giu];let m;while((m=patterns[0].exec(text)))addDamage(playerName(),m[1],"dom");while((m=patterns[1].exec(text)))addDamage(m[1],m[2],"dom");while((m=patterns[2].exec(text)))addDamage(m[1],m[2],"dom");while((m=patterns[3].exec(text)))addDamage(m[1],m[2],"dom");while((m=patterns[4].exec(text)))addDamage(m[2],m[1],"dom");}
  window.addEventListener("huntera-assist-packet",e=>parsePacket(e.detail?.payload));
  function observe(){const observer=new MutationObserver(()=>tryAutoAccept());observer.observe(document.documentElement,{childList:true,subtree:true});}
  const visible=el=>{const r=el.getBoundingClientRect(),s=getComputedStyle(el);return r.width>0&&r.height>0&&s.visibility!=="hidden"&&s.display!=="none";};
  function tryAutoAccept(){if(!state.settings.autoAccept||Date.now()<state.clickLock)return;for(const el of document.querySelectorAll("button,[role='button'],input[type='button'],input[type='submit'],a")){const label=(el.innerText||el.value||el.getAttribute("aria-label")||"").trim();if(!/^aceitar$/i.test(label)||!visible(el)||el.disabled)continue;let context="",parent=el;for(let i=0;i<5&&parent;i++,parent=parent.parentElement)context+=` ${parent.textContent||""}`;if(!/recusar|convite|invite|party|grupo|duelo|trade|troca/i.test(context))continue;state.clickLock=Date.now()+1500;el.click();chrome.storage.local.get({acceptedCount:0},d=>chrome.storage.local.set({acceptedCount:d.acceptedCount+1,lastAcceptedAt:Date.now()}));break;}}
  function format(v){if(v>=1e9)return`${(v/1e9).toFixed(2)}B`;if(v>=1e6)return`${(v/1e6).toFixed(2)}M`;if(v>=1e3)return`${(v/1e3).toFixed(2)}K`;return Math.round(v).toLocaleString("pt-BR");}
  function playerColor(name,index){const klass=/\[(MS|RP|EK|ED)\]\s*$/i.exec(name)?.[1]?.toUpperCase();return classColors[klass]||colors[index%colors.length];}
  function createPanel(){if(document.getElementById("huntera-assist"))return;const panel=document.createElement("aside");panel.id="huntera-assist";panel.innerHTML=`<header><span class="ha-title"><b>⚔</b> Damage Done</span><span class="ha-actions"><button data-action="compact" title="Modo compacto">≡</button><button data-action="collapse" title="Recolher">−</button><button data-action="reset" title="Reiniciar sessão">↻</button><button data-action="close" title="Ocultar">×</button></span></header><div class="ha-body"></div><footer><span class="ha-status-dot"></span><span>Sessão ativa</span><span class="ha-timer">00:00</span></footer>`;document.documentElement.appendChild(panel);panel.querySelector("[data-action='reset']").onclick=reset;panel.querySelector("[data-action='compact']").onclick=()=>{state.settings.compactMode=!state.settings.compactMode;panel.classList.toggle("compact",state.settings.compactMode);chrome.storage.sync.set({compactMode:state.settings.compactMode});};panel.querySelector("[data-action='close']").onclick=()=>{state.settings.dpsEnabled=false;chrome.storage.sync.set({dpsEnabled:false});panel.remove();};panel.querySelector("[data-action='collapse']").onclick=()=>{state.settings.panelCollapsed=!state.settings.panelCollapsed;panel.classList.toggle("collapsed",state.settings.panelCollapsed);chrome.storage.sync.set({panelCollapsed:state.settings.panelCollapsed});};panel.classList.toggle("collapsed",state.settings.panelCollapsed);panel.classList.toggle("compact",state.settings.compactMode);makeDraggable(panel,panel.querySelector("header"));render();}
  function makeDraggable(panel,handle){let drag;handle.addEventListener("pointerdown",e=>{if(e.target.closest("button"))return;const r=panel.getBoundingClientRect();drag={x:e.clientX-r.left,y:e.clientY-r.top};handle.setPointerCapture(e.pointerId);});handle.addEventListener("pointermove",e=>{if(!drag)return;panel.style.left=`${Math.max(4,Math.min(innerWidth-panel.offsetWidth-4,e.clientX-drag.x))}px`;panel.style.top=`${Math.max(4,Math.min(innerHeight-panel.offsetHeight-4,e.clientY-drag.y))}px`;});handle.addEventListener("pointerup",()=>drag=null);}
  function reset(){state.players.clear();state.startedAt=0;state.lastDamageAt=0;render();}
  function scheduleRender(){if(state.renderQueued)return;state.renderQueued=true;requestAnimationFrame(()=>{state.renderQueued=false;render();});}
  const escapeHtml=t=>t.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  function render(){const panel=document.getElementById("huntera-assist");if(!panel)return;const players=[...state.players.values()].sort((a,b)=>b.damage-a.damage).slice(0,12),total=players.reduce((s,p)=>s+p.damage,0),elapsed=Math.max(1,(Date.now()-(state.startedAt||Date.now()))/1000);panel.querySelector(".ha-body").innerHTML=players.length?players.map((p,i)=>{const share=total?p.damage/total*100:0;return`<div class="ha-row" style="--bar:${playerColor(p.name,i)};--size:${share.toFixed(1)}%"><span class="ha-rank">${i+1}.</span><span class="ha-name">${escapeHtml(p.name)}</span><strong>${Math.round(share)}%</strong><small>${format(p.damage/elapsed)}/s · ${p.hits} hits · maior ${format(p.maxHit||0)}${p.criticalHits?` · ${p.criticalHits} críticos`:""} · dano ${format(p.damage)}</small></div>`;}).join(""):`<div class="ha-empty">Aguardando dano de combate…<small>O painel será preenchido ao atacar.</small></div>`;panel.querySelector(".ha-timer").textContent=`${String(Math.floor(elapsed/60)).padStart(2,"0")}:${String(Math.floor(elapsed%60)).padStart(2,"0")}`;}
  chrome.runtime.onMessage.addListener((m,_,respond)=>{if(m.type==="settings"){Object.assign(state.settings,m.settings);if(state.settings.dpsEnabled)createPanel();else document.getElementById("huntera-assist")?.remove();document.getElementById("huntera-assist")?.classList.toggle("compact",state.settings.compactMode);respond({ok:true});}if(m.type==="reset"){reset();respond({ok:true});}});
  chrome.storage.sync.get(DEFAULTS,settings=>{state.settings=settings;const start=()=>{observe();if(settings.dpsEnabled)createPanel();setInterval(tryAutoAccept,700);setInterval(render,1000);};if(document.documentElement)start();else document.addEventListener("DOMContentLoaded",start,{once:true});});
})();
